stages:
  - test

test:
  image: python:3.7
  before_script:
    - python3 -m pip install --upgrade pip
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pytest tests/unittests/ --cov=core   --cov-report xml:../result.xml
